on:
  push:
    paths:
      - .github/**
      - setup.sh
      - README.md
  pull_request:
    paths:
      - .github/**
      - setup.sh
      - README.md
  workflow_dispatch:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: jmgilman
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run mdformat
        run: nix develop -c mdformat --wrap 80 --check README.md
      - name: Run markdownlint
        run: nix develop -c markdownlint README.md
      - name: Run shfmt
        run: nix develop -c shfmt -d setup.sh
      - name: Run shellcheck
        run: nix develop -c shellcheck setup.sh
      - name: Validate SHA
        run: shasum -a 256 -c setup.sh.sha256
